version: "3.8"

services:
  debian-mqtt:
    image: debian-mqtt
    container_name: remi-ctn
    environment:
      - BROKER_URI=tcp://192.168.x.y:1883
      - DEVICE_ID=IRsensor
      - USERNAME=device-iot
      - DEVICE_KEY=password

    #restart: unless-stopped
